const QUESTION_DATA = {
  

  '8': [
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'A certain number of men take 45 days to complete work. If there are 10 men less then they will take 60 days to complete the work. Find the original number of men.',
    correct_answer: '40',
    incorrect_answers: ['50', '60', '30'],
    options: ['50', '60', '30', '40'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: '5 men and 10 boys can do a piece of work in 30 days and 8 men and 12 boys can do the work in 20 days. What is the ratio of daily work done by a man to that of a boy?',
    correct_answer: '6:1',
    incorrect_answers: ['5:1', '4:5', '7:3'],
    options: ['5:1', '4:5', '6:1', '7:3'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: '4 women and 5 men working together can do 3 times the work done by 2 women and one man together. Calculate the work of a man to that of a woman.',
    correct_answer: '1:1',
    incorrect_answers: ['3:2', '1:2', '2:1'],
    options: ['1:1', '3:2', '1:2', '2:1'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Manoj can do a work in 20 days, while Chandu can do the same work in 25 days. They started the work jointly. A few days later Suresh also joined them and thus all of them completed the whole work in 10 days. All of them were paid a total of Rs.1000. What is the share of Suresh?',
    correct_answer: '100',
    incorrect_answers: ['300', '200', '400'],
    options: ['100', '300', '200', '400'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Nagarjuna lends Rs.30,000 to two of his friends. He gives Rs.15,000 to the first at 6% p.a. simple interest. He wants to make a profit of 10% on the whole. At what simple interest rate should he lend the remaining amount to the second friend?',
    correct_answer: '14%',
    incorrect_answers: ['8%', '12%', '16%'],
    options: ['8%', '12%', '14%', '16%'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'A portion of $6600 is invested at a 5% annual return, while the remainder is invested at a 3% annual return. If the annual income from the 5% investment is twice that of the 3% investment, what is the total income after one year?',
    correct_answer: '270',
    incorrect_answers: ['250', '280', '200'],
    options: ['270', '250', '280', '200'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'While calculating the weight of a group of men, the weight of one member was mistakenly written as 83 kg instead of 63 kg. As a result, the average weight increased by 0.5 kg. What is the number of men in the group?',
    correct_answer: '40',
    incorrect_answers: ['25', '20', '60'],
    options: ['25', '20', '40', '60'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'In a group of 8 boys, two boys aged 21 and 23 were replaced by two new boys. As a result, the average age of the group increased by 2 years. What is the average age of the two new boys?',
    correct_answer: '30',
    incorrect_answers: ['17', '28', '23'],
    options: ['17', '30', '28', '23'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'A boat takes a total of 16 hours for travelling downstream from point A to point B and returning to point C, which lies between A and B. If the speed of the boat in still water is 9 km/hr and the speed of the stream is 6 km/hr, what is the distance between A and C?',
    correct_answer: 'Cannot be determined',
    incorrect_answers: ['60 Km', '90 Km', '30 Km'],
    options: ['60 Km', '90 Km', '30 Km', 'Cannot be determined'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'A boat going upstream takes 8 hours 24 minutes to cover a certain distance, while it takes 5 hours to cover 5/7 of the same distance downstream. What is the ratio of the speed of the boat to the speed of the water current?',
    correct_answer: '11:1',
    incorrect_answers: ['11:5', '11:6', '6:5'],
    options: ['11:5', '11:6', '11:1', '6:5'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'A boat takes 128 minutes less to travel 48 km downstream than to travel the same distance upstream. If the speed of the stream is 3 km/hr, what is the speed of the boat in still water?',
    correct_answer: '12 Km/hr',
    incorrect_answers: ['15 Km/hr', '6 Km/hr', '9 Km/hr'],
    options: ['12 Km/hr', '15 Km/hr', '6 Km/hr', '9 Km/hr'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'An alloy contains Brass, Iron, and Zinc in the ratio 2:3:1 and another contains Iron, Zinc, and Lead in the ratio 5:4:3. If equal weights of both alloys are melted together to form a third alloy, what will be the weight of lead per kg in the new alloy?',
    correct_answer: '1/8',
    incorrect_answers: ['1/4', '41/7', '51/9'],
    options: ['1/4', '41/7', '1/8', '51/9'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'A milkman mixes 6 litres of water with 20 litres of pure milk. If the cost of pure milk is Rs.28 per litre, what is the percentage profit when he sells the mixture at the cost price of pure milk?',
    correct_answer: '30%',
    incorrect_answers: ['16(1/3)%', '25%', '16.5%'],
    options: ['30%', '16(1/3)%', '25%', '16.5%'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'A 144-litre mixture contains milk and water in the ratio 5:7. How much milk should be added so that the new ratio becomes 23:21?',
    correct_answer: '32 litres',
    incorrect_answers: ['40 litres', '28 litres', '36 litres'],
    options: ['40 litres', '28 litres', '32 litres', '36 litres'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'A shopkeeper bought 30 kg of rice at Rs.75 per kg and 20 kg of rice at Rs.70 per kg. He mixed them and sold the mixture at Rs.80 per kg. Find his gain.',
    correct_answer: 'Rs.350',
    incorrect_answers: ['Rs.550', 'Rs.420', 'Rs.210'],
    options: ['Rs.350', 'Rs.550', 'Rs.420', 'Rs.210'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'The cost price of 80 notebooks is equal to the selling price of 65 notebooks. What is the gain or loss percentage?',
    correct_answer: '23%',
    incorrect_answers: ['32%', '42%', '27%'],
    options: ['32%', '42%', '27%', '23%'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Eight years ago, Pranathi’s age was equal to the sum of the present ages of her son and daughter. Five years from now, the ratio of the daughter’s age to the son’s age will be 7:6. Pranathi’s husband is 7 years older than her and his present age is three times the present age of their son. What is the present age of the daughter?',
    correct_answer: '23 years',
    incorrect_answers: ['19 years', '27 years', '15 years'],
    options: ['19 years', '27 years', '15 years', '23 years'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Sha was married 8 years ago. Today her age is 9/7 times her age at the time of marriage. At present, her son’s age is 1/6 of her age. What was her son’s age 4 years ago?',
    correct_answer: '2 years',
    incorrect_answers: ['4 years', '3 years', '5 years'],
    options: ['4 years', '2 years', '3 years', '5 years'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'The present age ratio of Mani and Dheeraj is x:42. Mani is 8 years younger than Murali. Murali’s age after 8 years will be 33 years. The difference between Dheeraj’s and Mani’s ages equals Murali’s present age. Find the value of x.',
    correct_answer: '17',
    incorrect_answers: ['18', '10', '16'],
    options: ['18', '10', '16', '17'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Revanth’s present age is three times his son’s present age and 4/5 of his father’s present age. The average of their present ages is 62 years. What is the difference between the ages of Revanth’s father and his son?',
    correct_answer: '66 years',
    incorrect_answers: ['64 years', '69 years', '62 years'],
    options: ['64 years', '69 years', '66 years', '62 years'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the value of 36% of 945 − 26% of 765 + 17.7?',
    correct_answer: '159',
    incorrect_answers: ['167', '187', '143'],
    options: ['167', '187', '159', '143'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'What is the value of √(456 ÷ 12 + 142 − 11)?',
    correct_answer: '13',
    incorrect_answers: ['11', '169', '23'],
    options: ['11', '169', '23', '13'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: '1(1/5) of 1(1/2) of a number is 216. What is the number?',
    correct_answer: '120',
    incorrect_answers: ['100', '125', '140'],
    options: ['100', '125', '140', '120'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Find the next number in the series: 15, 32, 60, 122, 240, ?',
    correct_answer: '482',
    incorrect_answers: ['488', '364', '362'],
    options: ['488', '482', '364', '362'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Find the next number in the series: 18, 10, 8, 9, 11.5, ?',
    correct_answer: '14.75',
    incorrect_answers: ['10.75', '18.75', '19.75'],
    options: ['10.75', '18.75', '19.75', '14.75'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'Chess',
    incorrect_answers: ['Badminton', 'Cricket', 'Volleyball'],
    options: ['Chess', 'Badminton', 'Cricket', 'Volleyball'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'Compete',
    incorrect_answers: ['Win', 'Triumph', 'Victory'],
    options: ['Win', 'Compete', 'Triumph', 'Victory'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'Horse',
    incorrect_answers: ['Jackal', 'Cat', 'Dog'],
    options: ['Jackal', 'Horse', 'Cat', 'Dog'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'IK',
    incorrect_answers: ['YB', 'AD', 'MP'],
    options: ['YB', 'AD', 'IK', 'MP'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'RSTU',
    incorrect_answers: ['BCDF', 'KJNL', 'WXYZ'],
    options: ['BCDF', 'KJNL', 'RSTU', 'WXYZ'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'Avoid',
    incorrect_answers: ['Obstruct', 'Block', 'Hamper'],
    options: ['Avoid', 'Obstruct', 'Block', 'Hamper'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'Draupadi Murmu',
    incorrect_answers: ['Arvind Kejriwal', 'Siddaramaiah', 'Mukul Sangma'],
    options: ['Arvind Kejriwal', 'Siddaramaiah', 'Draupadi Murmu', 'Mukul Sangma'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'Cotton',
    incorrect_answers: ['Wheat', 'Corn', 'Millet'],
    options: ['Wheat', 'Corn', 'Millet', 'Cotton'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'Swan',
    incorrect_answers: ['Sparrow', 'Parrot', 'Koel'],
    options: ['Sparrow', 'Parrot', 'Swan', 'Koel'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Four of the following five are alike in a certain way and so form a group. Which is the one that does not belong to that group?',
    correct_answer: 'Nitrogen',
    incorrect_answers: ['Manure', 'Ammonia', 'Urea'],
    options: ['Manure', 'Ammonia', 'Urea', 'Nitrogen'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Statements: I. The bank decided to give advances to the priority sector at the rate of interest at par with the corporate sector. II. The percentage of bad loans given by the banks to the priority sector is very low compared to the corporate sector. Which of the following is correct?',
    correct_answer: 'Both I and II are effects of independent causes.',
    incorrect_answers: [
      'I is the cause and II is its effect.',
      'II is the cause and I is its effect.',
      'Both I and II are independent causes.'
    ],
    options: [
      'I is the cause and II is its effect.',
      'II is the cause and I is its effect.',
      'Both I and II are independent causes.',
      'Both I and II are effects of independent causes.'
    ],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Statements: I. Many seats in the private medical colleges in the state have remained vacant this year. II. The government medical colleges in the state could accommodate all the students who sought admission this year. Which of the following is correct?',
    correct_answer: 'II is the cause and I is its effect.',
    incorrect_answers: [
      'I is the cause and II is its effect.',
      'Both I and II are effects of independent causes.',
      'Both I and II are effects of some common causes.'
    ],
    options: [
      'I is the cause and II is its effect.',
      'II is the cause and I is its effect.',
      'Both I and II are effects of independent causes.',
      'Both I and II are effects of some common causes.'
    ],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Statements: I. The Ganges river is flooded due to large sheets of ice coming down from the Himalayas. II. Many people in the Himalayan ranges lost their houses under huge sheets of ice. Which of the following is correct?',
    correct_answer: 'Both I and II are effects of some common causes.',
    incorrect_answers: [
      'I is the cause and II is its effect.',
      'II is the cause and I is its effect.',
      'Both I and II are independent causes.'
    ],
    options: [
      'I is the cause and II is its effect.',
      'II is the cause and I is its effect.',
      'Both I and II are effects of some common causes.',
      'Both I and II are independent causes.'
    ],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'In a class of 20 students, Shreya is 5th from the top and Annie is 7 ranks below Shreya. Find Annie’s rank from the bottom.',
    correct_answer: '9',
    incorrect_answers: ['3', '5', '6'],
    options: ['3', '5', '6', '9'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Rita is sitting 5th from the left end of the row and Sita is 11th to the right of Rita. Tina is 4th to the left of Sita. Madhuri is 8th to the right of Tina. What is the total number of students in the row if Madhuri is sitting at the extreme end?',
    correct_answer: '20',
    incorrect_answers: ['28', '23', '33'],
    options: ['20', '28', '23', '33'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Karuna is sitting 25th from the left end and Preeti is sitting 26th from the right end. Preeti is 20th to the left of Karuna. What is the total number of students sitting in the row?',
    correct_answer: '30',
    incorrect_answers: ['21', '32', '26'],
    options: ['21', '32', '26', '30'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'In a row of 30 children, A is 11th from the right end. If there are 4 children between A and B, what is the position of B from the left end of the row?',
    correct_answer: 'Cannot be determined',
    incorrect_answers: ['5', '8', '4'],
    options: ['5', '8', '4', 'Cannot be determined'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Prerna is 5th from the left end and Charu is 4th from the right end of the row. Charu interchanges her position with the one sitting 3rd to the right of Prerna. Now Charu is 10th from the right end. How many children are there in the row?',
    correct_answer: '17',
    incorrect_answers: ['18', '20', '15'],
    options: ['18', '20', '15', '17'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Judge : Court :: Doctor : ?',
    correct_answer: 'Hospital',
    incorrect_answers: ['Municipality', 'Tehsil', 'Factory'],
    options: ['Municipality', 'Hospital', 'Tehsil', 'Factory'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Carbon dioxide : Extinguish :: Oxygen : ?',
    correct_answer: 'Burn',
    incorrect_answers: ['Foam', 'Explode', 'Isolate'],
    options: ['Foam', 'Explode', 'Burn', 'Isolate'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Kitten : Cat :: Cub : ?',
    correct_answer: 'Tiger',
    incorrect_answers: ['Deer', 'Giraffe', 'Horse'],
    options: ['Tiger', 'Deer', 'Giraffe', 'Horse'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Den : Lion :: Stable : ?',
    correct_answer: 'Horse',
    incorrect_answers: ['Cat', 'Dog', 'Cow'],
    options: ['Cat', 'Dog', 'Horse', 'Cow'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'Thermometer : Temperature :: Barometer : ?',
    correct_answer: 'Pressure',
    incorrect_answers: ['Stress', 'Strain', 'Force'],
    options: ['Stress', 'Pressure', 'Strain', 'Force'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'In which year was Sugan born?\n\nI. Sugan’s present age is 20 years more than his child.\nII. Sugan has two children. The first child was born in 1993.',
    correct_answer: 'Neither I nor II',
    incorrect_answers: ['Only I', 'Only II', 'Both I and II'],
    options: ['Only I', 'Only II', 'Both I and II', 'Neither I nor II'],
  },
  {
    category: 'miscellaneous',
    type: 'multiple',
    difficulty: 'medium',
    question: 'How many students secured First Class in a class of 50 students?\n\nI. Double the number of First Class students secured Second Class and all the remaining students failed.\nII. The number of students who failed was twice the number of First Class students.',
    correct_answer: 'Both I and II',
    incorrect_answers: ['Only I', 'Only II', 'Either I or II'],
    options: ['Only I', 'Only II', 'Both I and II', 'Either I or II'],
  },
],

  
  '9': [
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'medium',
      question: 'If the ratio of two numbers is 3:5 and their sum is 64, what is the larger number?',
      correct_answer: '40',
      incorrect_answers: ['24', '36', '32'],
      options: ['24', '32', '40', '36'],
    },
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'easy',
      question: 'What is 15% of 200?',
      correct_answer: '30',
      incorrect_answers: ['20', '25', '35'],
      options: ['20', '25', '30', '35'],
    },
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'medium',
      question: 'A train travels 180 km in 2 hours. What is its average speed in km/h?',
      correct_answer: '90',
      incorrect_answers: ['80', '100', '85'],
      options: ['80', '85', '90', '100'],
    },
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'medium',
      question: 'A shopkeeper sells an item for $240 with a 20% profit. What was the cost price?',
      correct_answer: '200',
      incorrect_answers: ['180', '220', '210'],
      options: ['180', '200', '210', '220'],
    },
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'hard',
      question: 'If x + 2y = 14 and 2x - y = 3, what is the value of x?',
      correct_answer: '5',
      incorrect_answers: ['4', '6', '7'],
      options: ['4', '5', '6', '7'],
    },
  ],
  '10': [
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'medium',
      question: 'Find the next number in the sequence: 2, 4, 7, 11, 16, ?',
      correct_answer: '22',
      incorrect_answers: ['21', '24', '23'],
      options: ['21', '22', '23', '24'],
    },
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'easy',
      question: 'If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are definitely Lazzies. Is the statement true or false?',
      correct_answer: 'True',
      incorrect_answers: ['False', 'Cannot say', 'Only sometimes'],
      options: ['True', 'False', 'Cannot say', 'Only sometimes'],
    },
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'medium',
      question: 'Which one of the following is the odd one out: Apple, Carrot, Banana, Mango?',
      correct_answer: 'Carrot',
      incorrect_answers: ['Apple', 'Banana', 'Mango'],
      options: ['Apple', 'Carrot', 'Banana', 'Mango'],
    },
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'hard',
      question: 'In a code language, if TRAIN is written as UISCR, how is PLANE written?',
      correct_answer: 'QMBNF',
      incorrect_answers: ['QMANF', 'QMBOE', 'QMBNE'],
      options: ['QMBNF', 'QMANF', 'QMBNE', 'QMBOE'],
    },
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'medium',
      question: 'A clock shows 3:00. What is the angle between the hour and minute hands?',
      correct_answer: '90°',
      incorrect_answers: ['60°', '120°', '45°'],
      options: ['45°', '60°', '90°', '120°'],
    },
  ],
  '11': [
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What is the output of the expression `2 + 3 * 4` in most programming languages?',
      correct_answer: '14',
      incorrect_answers: ['20', '24', '10'],
      options: ['10', '14', '20', '24'],
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'easy',
      question: 'Which HTML tag is used to define an unordered list?',
      correct_answer: '<ul>',
      incorrect_answers: ['<ol>', '<li>', '<list>'],
      options: ['<ul>', '<ol>', '<li>', '<list>'],
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'medium',
      question: 'In JavaScript, which keyword is used to declare a constant?',
      correct_answer: 'const',
      incorrect_answers: ['let', 'var', 'static'],
      options: ['let', 'var', 'const', 'static'],
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'What is the ASCII value of space?',
      correct_answer: '32',
      incorrect_answers: ['31', '33', '34'],
      options: ['31', '32', '33', '34']
    },
      {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'choose the correct option. \n #include<stdio.h>\n\t\t void main(){int a=97\n\t\t printf("%c", a);}',
      correct_answer: 'a',
      incorrect_answers: ['d', 'k', 'p'],
      options: ['a', 'd', 'k', 'p']
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'Which data structure uses LIFO order?',
      correct_answer: 'Stack',
      incorrect_answers: ['Queue', 'Tree', 'Graph'],
      options: ['Queue', 'Stack', 'Tree', 'Graph'],
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'How many keywords are present in C programming?',
      correct_answer: '32',
      incorrect_answers: ['31', '33', '34'],
      options: ['31', '32', '33', '34']
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'What is the size of a char datatype in C?',
      correct_answer: '1',
      incorrect_answers: ['2', '4', '8'],
      options: ['1', '2', '4', '8']
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What does CSS stand for?',
      correct_answer: 'Cascading Style Sheets',
      incorrect_answers: ['Computer Style Sheets', 'Creative Style System', 'Cascading System Script'],
      options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style System', 'Cascading System Script'],
    },
  ],
};

export default QUESTION_DATA;
