const QUESTION_DATA = {
  '9': [
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'medium',
      question: 'If the ratio of two numbers is 3:5 and their sum is 64, what is the larger number?',
      correct_answer: '40',
      incorrect_answers: ['24', '36', '32'],
      options: ['24', '32', '40', '36'],
    },
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'easy',
      question: 'What is 15% of 200?',
      correct_answer: '30',
      incorrect_answers: ['20', '25', '35'],
      options: ['20', '25', '30', '35'],
    },
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'medium',
      question: 'A train travels 180 km in 2 hours. What is its average speed in km/h?',
      correct_answer: '90',
      incorrect_answers: ['80', '100', '85'],
      options: ['80', '85', '90', '100'],
    },
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'medium',
      question: 'A shopkeeper sells an item for $240 with a 20% profit. What was the cost price?',
      correct_answer: '200',
      incorrect_answers: ['180', '220', '210'],
      options: ['180', '200', '210', '220'],
    },
    {
      category: 'Apptitude',
      type: 'multiple',
      difficulty: 'hard',
      question: 'If x + 2y = 14 and 2x - y = 3, what is the value of x?',
      correct_answer: '5',
      incorrect_answers: ['4', '6', '7'],
      options: ['4', '5', '6', '7'],
    },
  ],
  '10': [
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'medium',
      question: 'Find the next number in the sequence: 2, 4, 7, 11, 16, ?',
      correct_answer: '22',
      incorrect_answers: ['21', '24', '23'],
      options: ['21', '22', '23', '24'],
    },
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'easy',
      question: 'If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are definitely Lazzies. Is the statement true or false?',
      correct_answer: 'True',
      incorrect_answers: ['False', 'Cannot say', 'Only sometimes'],
      options: ['True', 'False', 'Cannot say', 'Only sometimes'],
    },
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'medium',
      question: 'Which one of the following is the odd one out: Apple, Carrot, Banana, Mango?',
      correct_answer: 'Carrot',
      incorrect_answers: ['Apple', 'Banana', 'Mango'],
      options: ['Apple', 'Carrot', 'Banana', 'Mango'],
    },
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'hard',
      question: 'In a code language, if TRAIN is written as UISCR, how is PLANE written?',
      correct_answer: 'QMBNF',
      incorrect_answers: ['QMANF', 'QMBOE', 'QMBNE'],
      options: ['QMBNF', 'QMANF', 'QMBNE', 'QMBOE'],
    },
    {
      category: 'Reasoning',
      type: 'multiple',
      difficulty: 'medium',
      question: 'A clock shows 3:00. What is the angle between the hour and minute hands?',
      correct_answer: '90°',
      incorrect_answers: ['60°', '120°', '45°'],
      options: ['45°', '60°', '90°', '120°'],
    },
  ],
  '11': [
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What is the output of the expression `2 + 3 * 4` in most programming languages?',
      correct_answer: '14',
      incorrect_answers: ['20', '24', '10'],
      options: ['10', '14', '20', '24'],
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'easy',
      question: 'Which HTML tag is used to define an unordered list?',
      correct_answer: '<ul>',
      incorrect_answers: ['<ol>', '<li>', '<list>'],
      options: ['<ul>', '<ol>', '<li>', '<list>'],
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'medium',
      question: 'In JavaScript, which keyword is used to declare a constant?',
      correct_answer: 'const',
      incorrect_answers: ['let', 'var', 'static'],
      options: ['let', 'var', 'const', 'static'],
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'What is the ASCII value of space?',
      correct_answer: '32',
      incorrect_answers: ['31', '33', '34'],
      options: ['31', '32', '33', '34']
    },
      {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'choose the correct option. \n #include<stdio.h>\n\t\t void main(){int a=97\n\t\t printf("%c", a);}',
      correct_answer: 'a',
      incorrect_answers: ['d', 'k', 'p'],
      options: ['a', 'd', 'k', 'p']
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'Which data structure uses LIFO order?',
      correct_answer: 'Stack',
      incorrect_answers: ['Queue', 'Tree', 'Graph'],
      options: ['Queue', 'Stack', 'Tree', 'Graph'],
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'How many keywords are present in C programming?',
      correct_answer: '32',
      incorrect_answers: ['31', '33', '34'],
      options: ['31', '32', '33', '34']
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'hard',
      question: 'What is the size of a char datatype in C?',
      correct_answer: '1',
      incorrect_answers: ['2', '4', '8'],
      options: ['1', '2', '4', '8']
    },
    {
      category: 'Coding',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What does CSS stand for?',
      correct_answer: 'Cascading Style Sheets',
      incorrect_answers: ['Computer Style Sheets', 'Creative Style System', 'Cascading System Script'],
      options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style System', 'Cascading System Script'],
    },
  ],
};

export default QUESTION_DATA;
